SELECT JSON_OBJECT(
	'ROZA_ID', 1,
	'ROZA_TITLE', 'PN/PK/HQ/18/270/2017',
	'ROZA_DESC', 'MAKLUMAT ASAS BELUM DIAGIHKAN',
	'ROZA_TIME', '12/04/17 14:00',
	'PROCESS_ID', 'ADJ',
	'MODULE_ID', 'A'
)
UNION
SELECT JSON_OBJECT(
	'ROZA_ID', 4,
	'ROZA_TITLE', 'PN/PK/HQ/18/278/2017',
	'ROZA_DESC', 'AGIHAN DAN KLASIFIKASIxx',
	'ROZA_TIME', '12/04/17 14:30',
    'PROCESS_ID', 'ADJ',
	'MODULE_ID', 'A'
)
UNION
SELECT JSON_OBJECT(
	'ROZA_ID', 2,
	'ROZA_TITLE', 'PN/PK/HQ/18/280/2017',
	'ROZA_DESC', 'PERINCIAN MAKLUMAT KERTAS SIASATAN DAN PENGHAKIMAN',
	'ROZA_TIME', '12/04/17 15:30',
	'PROCESS_ID', 'ADJ',
	'MODULE_ID', 'B'
)
UNION
SELECT JSON_OBJECT(
	'ROZA_ID', 3,
	'ROZA_TITLE', 'PN/PP/SFC/07/23/2017',
	'ROZA_DESC', 'PENGESAHAN PENUTUPAN FAIL',
	'ROZA_TIME', '12/04/17 15:30',
	'PROCESS_ID', 'ADJ',
	'MODULE_ID', 'B'
)
UNION
SELECT JSON_OBJECT(
	'ROZA_ID', 5,
	'ROZA_TITLE', 'PN/PP/SFC/07/22/2017',
	'ROZA_DESC', 'PENUTUPAN FAIL',
	'ROZA_TIME', SYSDATE(),
	'PROCESS_ID', 'TMT',
	'MODULE_ID', 'B'
)